### ISSUE TITLE
Relationship to Software/Data Carpentry

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#7]
Following on from @tracykteal https://github.com/data-lessons/librarycarpentry/issues/6#issuecomment-244492755

To consider:
- Software Carpentry has been coordinating Library focused Software Carpentry events, that I think have even been called Library Carpentry. Do you want this to continue?
- If and what support and relationship does LC want from SWC/DC in terms of instructors, templating and such?
- What _rules_ do we want around workshops that use both LC and SWC/DC materials? (given that the latter require at least one SWC/DC qualified instructor)

cc @tracykteal @pitviper6 @weaverbel

**Comment by jezcope** [comment]
I think my understanding was that you can use the SWC/DC materials all you want, but you have to fulfil the conditions (e.g. at least one qualified instructor) to *advertise* it as SWC/DC. Is that correct?

**Comment by cmacdonell** [comment]
My thoughts:

- I think we want to maintain the relationship with SWC/DC.  LC currently lacks a benevolent dictator, rather it is a team effort with regional leaders.   Therefore I think it's beneficial to have SWC/DC be at least a first point of contact that can then direct inquiries to the appropriate LC person.
- I would highly suggest that LC workshops have at least one SWC/DC-certified instructor.  I consider anything "Carpentry" as part of the brand and we, LC, should protect that brand by following very similar guidelines.  Plus, I think the instructor training is extremely valuable.  As for templating, our newer lessons under the data-lessons account are already using the new SWC template which I quite like.
- I think @jezcope is right.  SWC/DC materials are licensed as CC meaning they can be freely used by anyone as long as SWC/DC are attributed.  And I think it's OK to mix lessons (we did this in the SA workshop last week.)

**Comment by drjwbaker** [comment]
Concur that @jezcope is correct. On 'Carpentry', I used this with approval from SWC on the understanding that LC was exploratory and thus wouldn't impact on the brand. In all honesty, in retrospect, I'd have called it Software Skills for Librarians (but let's not go there).

On certified instructors. I am loath to impose this. I see the LC model working a little differently in that we're trying to encourage people to take the materials and reuse them as works best in their professional setting. Sometimes this means 'workshops', at which - I'm minded - we recommend having a SWC/DC-certified trainer. If we do, we need to figure out how - without asking us - someone wishing to run a workshop would go about engaging a SWC/DC-certified trainer. I'm minded that we encourage a similar route to that which exists: the organiser agrees to pay for their travel/accommodation et al. Perhaps we hack bits from http://software-carpentry.org/workshops/operations/ that fits what we need? (and check with SWC/DC so they know we are directing people to them to find an approved instructor if they want one)

**Comment by ostephens** [comment]
It feels like if we continue to use 'carpentry' then we are drawing on the SWC/DC brand. I feel slightly uncomfortable doing this if we do not do this following the approach of SWC/DC (i.e. require a qualified instructor when using 'carpentry' in the name)

**Comment by cmacdonell** [comment]
Our ultimate goal is to ensure workshop quality so that our learners are satisfied with the time and money they've spent.  Satisfied learners also protects the Carpentry brand.  I chose my words carefully to *highly recommend* a certified instructor, but grabbing any SWC/DC instructor who is unaware of the library audience is probably not going to ensure a quality workshop either.  So I would agree that imposing it as a requirement is unwise at the moment.

Belinda suggested having a chat soon about the LC future, I look forward to it.

**Comment by Repositorian** [comment]
Adding a few more cents from a Library Administrator perspective at a US Research Library; we are in the process of joining the Carpentry organization as a paying institutional member with the expectation that up to six of our instructors will be Carpentry Certified in 2017.  In that way, we will be properly able to support the Carpentry brand, mission, and teaching approaches while also opening up a nice channel through which to customize and augment the workshops we offer at Caltech. The Author Carpentry lessons seem to be of most compelling value here, where Library Instructors teach researchers on authorship and publishing aspects of sharing open data, software, and papers (increasingly, as an integrated executable Paper of the Future). Our vision is to bolster and advance the Carpentry movement as much as possible and preserve the power of that instructional movement!

In our experience, Library Carpentry goes by other names and operates under other banners here in the US and so we are less inclined to teach these programs in our community. Many of us with good data science skills share our knowledge and skills via non-Carpentry venues: Code4Lib community; E-Science and Research Data Librarians community; DH+Lib for digital humanities programming and data wrangling; and the many many initiatives around open linked data (VIVO, Open knowledge bases for bibliographic and e-resources metadata).

**Comment by drjwbaker** [comment]
*Instructors**: thinking about https://github.com/data-lessons/librarycarpentry/issues/6 and given where we are, I like the wording:

> To maintain the quality of Library Carpentry workshops, it is highly recommend that a Software/Data Carpentry certified instructor is present at each workshop. For more on Software/Date Carpentry instructors and instructor training, see http://software-carpentry.org/join/

If quora, I'll add it to the blurb

**Chat**: the blurb at https://github.com/data-lessons/librarycarpentry/issues/6 is intended as a baseline for the proposed chat @cmacdonell mentions, so that we have a statement of what we think we are to work from. I *think* October was earmarked for a chat. I guess we should Doddle Poll!

@Repositorian: I'm a very much aware and inspired by the software skills work available in the US, especially via Code4Lib and Data Science for Librarians. One of my rationales for Library Carpentry was that I felt these fitted at big US research library model/practices well, but were less well suited to the smaller university libraries common in the UK. Obviously Library Carpentry is for UK folks, but it has obviously worked outwards from here, where Code4Lib et al are - as far as I can tell - much less influential/known.

**Comment by pitviper6** [comment]
My thoughts on the SWC rules:

I'd like to apply them to LC as far as possible. There is very much a branding consideration here, and one of the big pluses about SWC is its emphasis on pedagogy, community and commitment to quality learning. I went through the instructor training and I cannot emphasize how valuable it is, and how much I learned.

Pros: branding, quality, clarity on what LC is and does
Cons: some may find the SWC rules intimidating, and they may also be a roadblock as far as getting institutions to support participation by their staff.  Also, SWC instructor training is already on a long waiting list, and if you aren't part  of a member institution, you don't get those automatic slots. We don't want LC to wither due to lack of qualified instructors to head workshops.

What about saying (for now, anyway) that an SWC instructor isn't necessary to hold an LC workshop, but that the lead instructor for an LC workshop will be appointed a mentor who has gone through the SWC training and has taught a workshop, to dispense advice and guide them through the process? 

I say we also allow our materials to be used freely for one-off lessons, tutorials, etc. without branding it an LC workshop, and state that very clearly.

**Comment by Repositorian** [comment]
So this thread may be exposing some divergent assumptions held amongst the group of us: like blind monks each describing the body part of an elephant without realizing the limits of their respective views. There is a much different whole but each observer can't see it.

In the case of this LC discussion, I'm not sure what that whole is. There is clearly a shared passion for seeing librarians benefit from the skills and quality instruction offered by SWC/DC. But the details are of course trickier to work out.

My own skewed perspective as one blind monk is to question why SWC/DC need to be specialties for one particular profession : why the base lessons couldn't be used with library- based data and use cases. The SWC carpentry I attended at the USGS used earth science problems and data but the principles and skills were triple blue Carpentry. Why couldn't that apply to Librarians?  

The reason that Caltech librarians got interested in applying Carpentry to our work was because we believe in that community and model as is. As agents over our own professional practice, we pick and choose from the diversity of instructional opportunities and SWC/DC are a great fit for training everyone on our campus, including the librarians as partners in the research enterprise.

The reason we have spun off the CArpentry approach for Author Carpentry is because this program covers additional skills in research communication, publication, citation, and impact assessment that Greg Wilson was looking for help with. SWC has an authorship lesson that we are hoping to help refine and extend. 

Finally, it seems important to say this to nice and kindly colleague monks who are not practicing library professionals: the library profession is a huge tent, just as huge and diverse as, say, a community of biologists, or geologists, or humanists. Not all librarians work on bibliographic data from a catalog. Probably half of our procession doesn't deal with books or catalogs period. For this reason, it might be helpful to make sure that librarians preserve agency over the training others are offering and promoting on our behalves. The idea that SWC-LC would serve as the POC for LC is a concern for that reason. LIbrarian monks may be more effective in determining what training would fit what use cases or meet professional needs. Not sure how to connect librarian monks with SWC-DC central, but am happy to discuss ideas.

**Comment by drjwbaker** [comment]
> What about saying (for now, anyway) that an SWC instructor isn't necessary to hold an LC workshop, but that the lead instructor for an LC workshop will be appointed a mentor who has gone through the SWC training and has taught a workshop, to dispense advice and guide them through the process?

@pitviper6 agreed, if SWC are happy to receive enquiries of this nature.

> The SWC carpentry I attended at the USGS used earth science problems and data but the principles and skills were true blue Carpentry. Why couldn't that apply to Librarians? 

@Repositorian For me it is because SWC is aimed at research scientists and DC at researchers. Librarianship is - I agree - a HUGE tent and some librarians have happily attended SWC and parsed the lessons into their own contexts (including me when I worked in a library!), but others aren't so research orientated and want to see problems/contexts they recognise in the professional development they attend. LC spun out of work I did at the British Library on an internal digital scholarship programme where we took training and adapted it for library problems/contexts or hired trainers to tailor lessons based on their expertise for library problems/contexts. The LC pilot then came out of discussing those efforts at the BL with Greg and his observation that librarians were attending SWC and that tailored lessons might be worth looking into. The LC pilot suggested that among a bunch of self-selection librarians in from the South of England there is an appetite of this (see https://www.software.ac.uk/blog/2015-12-03-why-information-profession-needs-library-carpentry-0). I am very open minded about whether or not LC needs to be a 'thing' or not, but I do think that there is a software skills training need in the library profession that is not met by researcher focused events like SWC/DC (which is no criticism of SWC or DC, quite right they focused on the needs of researchers, and primarily scientists, and I don't want to see that diluted in any way). I hope that LC can provide that in some way.

**Comment by drjwbaker** [comment]
Oh, and on the agency point: yes, totally agree, we need as many librarians as possible involved and this is top of my agenda.

**Comment by pitviper6** [comment]
Repositorian:

I've thought about this as well. There is definitely a plug-and-play aspect to the SWC/DC/LC model, in that you are teaching the same tool with different datasets depending on the discipline. However, as far as I can tell from the lessons we've taught, there isn't much, if any, difference in what features of the tools are presented or emphasized. Maybe this is different for tools like R or Python, or for visualization of data.  But for Shell/Bash/Git/OpenRefine, the basics are the same (well, Git has some differences but it's more about approach than type of data).

A potential model is one base lesson originating with SWC, with extra exercises geared towards discipline-specific datasets that are maintained by DC/LC and could be used either during a workshop as collaborative exercises, or take-aways to work on afterwards as lesson reinforcements?

Throwing this out there as an observation, not as an absolute!

**Comment by ostephens** [comment]
Do we also need to approach this question from the other side - what relationship is SWC/DC willing to have with LC?

**Comment by drjwbaker** [comment]
> A potential model is one base lesson originating with SWC, with extra exercises geared towards discipline-specific datasets that are maintained by DC/LC and could be used either during a workshop as collaborative exercises, or take-aways to work on afterwards as lesson reinforcements?

SWC based with discipline-specific is, if I understand correctly, what DC are trying to achieve. Hence discussions I've had with @mkuzak about the viability or otherwise of migrating LC examples into DC.

> Do we also need to approach this question from the other side - what relationship is SWC/DC willing to have with LC?

A year ago: go ahead, do things, see what happens. Today: https://github.com/data-lessons/librarycarpentry/issues/6 feels to me like the starting point for that conversation. I'm minded that we have to know what we think we are, before reaching out to SWC/DC to figure out what relationship they want with us.

**Comment by cmacdonell** [comment]
@Repositorian being one of the non-librarians here I appreciate your comment about the Big Tent.  I might even argue that the librarian tent is broader than some/most other fields that SWC/DC target.  I believe this broadness is what makes the LC "elephant" so difficult to describe.  

My hunch is that defining LC as precisely as SWC/DC are currently described may be a mistake, excluding more than it includes.  As @drjwbaker mentions, perhaps LC need not be a "thing", but rather a community that helps librarians acquire software skills through workshops that draw on the best resources available wherever those resources may come from.

**Comment by tracykteal** [comment]
Sorry to be late to the discussion. You're right that yes, SWC/DC lessons are CC-BY and can be taught and used by anyone. To be called a SWC or DC workshop, they need to follow our guidelines. For both that means at least one qualified instructor and teaching our curriculum. DC guidelines here: http://www.datacarpentry.org/workshops/.

It's been great to see the development of these lessons and the demand for them over the last year. I think it's clear that there is are communities interested both in taking and teaching these workshops. 

@drjwbaker is absolutely right that DC is designed to be discipline-specific, so including the Library audience is within our goals and mission. I wanted to start this thread to see if there was interest from the people doing the development in making a more formal arrangement. I agree that https://github.com/data-lessons/librarycarpentry/issues/6 is the starting point.

I think you could have Library Carpentry both ways. I think you could get the support of the SWC/DC community by having more of a formal relationship, but for these lessons don't require that self-organized workshops have a badged SWC/DC instructor, so you could use your criteria to decide what makes it OK to call a workshop Library Carpentry. There is value to setting out this criteria, so that when people see a Library Carpentry workshop advertised, they have some clear expectations about what and how things will be taught. It's also useful for instructors to have these guidelines when they're putting a workshop together. 

For lesson development, that would still all be in the existing developers hands. For DC, we have two lesson maintainers for each module, and then an overall 'workshop maintainer' that provides oversight for the overall workshop content. So, you could follow a format like that.

Advantages to being a part of SWC/DC
- a place to refer people if they want a Library Carpentry workshop, but can't self-organize one, or don't have local instructors
- the possibility of training instructors (we could potentially do an online one focused just on people who want to teach Library Carpentry)
- committment to long-term maintenance, being a part of our lesson maintenance program
- access to SWC/DC infrastructure 
- using SWC/DC lesson templates (maybe a disadvantage)
- inclusion in the SWC/DC assessment program
- discoverability and branding: people look to SWC/DC for workshops on software and data skills, and they could then also find Library materials there
- promotion: SWC/DC give many talks a year. We can mention the Library Carpentry materials in talks and publications (although, I already point people to the work you're doing) 

Potential disadvantages:
- Potentially more oversight. If these are 'Carpentry' workshops, then we do want to continue to oversee them to make sure they're consistent and high-quality. 
- If we do require one badged instructor, it would be potentially harder to have people teach workshops called Library Carpentry
- using SWC/DC lesson templates (maybe an advantage)
- potential perception that SWC/DC is for researchers, and therefore materials associated with SWC/DC wouldn't be for the library community as @Repositorian and @drjwbaker mention

I can develop this further and put together an idea of what this might look like if you're interested.

**Comment by weaverbel** [comment]
As a former librarian and certified SWC/DC instructor, I have no problems teaching Library Carpentry. I definitely draw on my SWC/DC training when I teach but I am also prosetlytising a bit for the future with librarians, i.e. encouraging them to champion the Markdown/pandoc path so we end up with machine-readable data instead of the black boxes of Word documents and PDFs, encouraging them to venture into the world of open source Linux OS and Open Office rather than supporting expensive systems like Apple and Microsoft and to teach those skills to others, and so on. I bring in programminghistorian.org lessons and other stuff so my Library Carpentry is very free range ... but I think it gives people something to chew on, rather than just showing them tools ...  

I think it would be good to have a meet up soon - LC has just exploded since the sprint and it would be good to set some markers for where we are and where we want to end up.

**Comment by drjwbaker** [comment]
Okay. If you've forgive me briefly putting a 'benevolent dictator' hat on, I think we need the chat.

I can see three major items of discussion:

1) The blurb https://github.com/data-lessons/librarycarpentry/issues/6 Is this how we see ourselves now?
2) The Advantages/Disadvantages of being part of SWC/DC that @tracykteal set out above https://github.com/data-lessons/librarycarpentry/issues/7#issuecomment-245359513 ( @tracykteal thank you so much for this). What do we think of these? Where are we each minded?
3) Given our answers to 2), what trajectory do we set for 1). Where do we want 1) to be in 6, 12, 18 months? (taking into account, per basic project management, that you review the 12 and 18 month 'targets' at the 6 month mark with the assumption that they will change because contexts change)

Who then wants in on said discussion? If we can get a show of hands here, I'll circulate a Doodle Poll (on which: is there any time of day that works for a team from AET/GMT/PTZ!)

**Comment by timtomch** [comment]
I'm interested in participating in that discussion!

**Comment by jezcope** [comment]
Count me in, please!

**Comment by ostephens** [comment]
+1

**Comment by cmacdonell** [comment]
Count me in

**Comment by pitviper6** [comment]
+1, although being in the middle of the US, I may be iffy depending on the time!

**Comment by timtomch** [comment]
Time might be challenging: https://www.timeanddate.com/worldclock/meetingtime.html?p1=240&p2=136&p3=250&p4=137

Best bet looks to be something like 21:00 UTC, if our UK friends are OK with a meeting at 10PM.

**Comment by tracykteal** [comment]
+1 thanks for scheduling!

**Comment by chodacki** [comment]
+1

**Comment by Repositorian** [comment]
+1 Glad for the chance to discuss and explore options!

**Comment by jezcope** [comment]
21:00UTC/22:00BST is fine for me most nights

**Comment by jt14den** [comment]
+1 Count me in as well.

**Comment by weaverbel** [comment]
I am in, time zones permitting

**Comment by ccronje** [comment]
I think LC offers a pathway to change in both library practice and our relevance to researchers who increasingly practice open science/research methods. My Library is starting to sit up and take notice now that the University is seeking DC/SWC membership. From what I've observed internally, management are not quite sure what LC/DC/SWC is about, but at the same time concerned we're falling behind in supporting researchers applying new skills (e.g. How do we support researchers who text and data mine literature? How do we better support research data management in the context of open science? How do we up-skill staff so we can do this?). With LC I see possibility for change by leveraging DC/SWC's momentum and impact. As mentioned above, 'community' is key.

**Comment by drjwbaker** [comment]
@ccronje I totally agree that supporting researchers taking computational approaches is something LC can support. I also think this is the easy option, low hanging fruit et cetera, to just do that. Given the massive variety of librarianship, it feels important to me that we reach people with a) less obvious use cases b) don't necessarily support researchers day to day.

**Comment by drjwbaker** [comment]
Doodle Poll: http://doodle.com/poll/zwbdqnnxiz22s6nu

Per http://doodle.com/poll/zwbdqnnxiz22s6nu I've picked the two slots where everyone would be joining at a reasonable(ish) time. Once we have a time/date that most people can make (presuming not everyone will be able to), we'll need volunteers for chair, writing the agenda, and note-taking (perhaps a duo). Thanks all!

**Comment by drjwbaker** [comment]
Can I just check, you are all seeing this Doodle in your own timezones, correct? (so for me, it is showing 2pm and 10pm)

**Comment by tracykteal** [comment]
Yes, I see it in my timezone (6am and 2pm Pacific)

**Comment by cmacdonell** [comment]
Yes for me too

**Comment by Repositorian** [comment]
Yes, I see it in the correct timezone for my location. thanks!

**Comment by drjwbaker** [comment]
This for confirming. I was worried for a minute that I might commit some terrible timetabling disaster!

**Comment by drjwbaker** [comment]
Right. Monday 24 October at 2pm is London as come out as the best time, however with the vagaries of time zone changes that I didn't take into acount (sorry!) I've checked that is midnight in Sydney and 6am in LA... https://www.timeanddate.com/worldclock/meetingtime.html?day=24&month=10&year=2016&p1=240&p2=136&p3=250&p4=137&iv=0

**Comment by drjwbaker** [comment]
But that week has a good slot: 7am Syndey, 9pm London, 4pm Toronto, 1pm LA. So I'll revise the Doddle..

**Comment by drjwbaker** [comment]
Revised http://doodle.com/poll/zwbdqnnxiz22s6nudsazwg57/admin#table (with apologies I know you are all busy!)

**Comment by pitviper6** [comment]
Looking forward to a great discussion!  I wanted to add some developments that are coming out of the success of the LC workshop at UCSD. We started hearing from the other UC campuses that they also wanted to hold workshops, and so I contacted John Chodacki at CDL/UC3, since they have contacts with all of the campuses and would be in a great position to coordinate a University of California LC 'roadshow'.  In  addition, we've discussed holding some curriculum development hackathons in the future. I've pointed John to the LC github repository and he'll also be on the call, because we definitely want to develop our roadshow workshop in coordination with how the LC community sees it's development happening in the next five years (because community is one of the most important assets of the Carpentry model!)

**Comment by drjwbaker** [comment]
Big +1 @pitviper6

**Comment by chodacki** [comment]
As @pitviper6 mentioned, my team has been looking into ways to facilitate library training programs. We have resourcing this program internally and actively pursuing external funding as well. We plan to utilize our library communities like LC and also leverage existing organizations like DC/SWC. As you all know, when you start these types of relationships, it requires setting some lightweight structure so we can avoid conflicts down the road. I am happy to be involved in this LC discussion and that we are exploring what our relationship can/should be with DC/SWC.  We will need those orgs to understand our expectations so we don’t end up becoming bottlenecks for each other in the future. Looking forward to the call.

**Comment by drjwbaker** [comment]
**MEETING UPDATE**

Current best date/time based on the Doodle is Thursday 6 October at 2pm in the UK and these slightly awful times https://www.timeanddate.com/worldclock/meetingdetails.html?year=2016&month=10&day=6&hour=13&min=0&sec=0&p1=240&p2=136&p3=250&p4=137 elsewhere (no idea how I ended up on the call at a nice time..) Anyway, I've yet to hear from @weaverbel who is on leave. So if we are happy to proceed with this time, please pencil it into your diaries until we hear from Belinda (who I really really want to be part of this because, as most of you know, she has done more than anyone over the last 6 months to push LC forward).

Does anyone have a preference for what service we use for the meeting?

**Comment by ostephens** [comment]
+1 to having @weaverbel on this call.
Google Hangouts would work for me as a service for the meeting, but no strong preference

**Comment by drjwbaker** [comment]
I'm happy with Hangouts, though with video and mics off by default (turn them on when you want to talk). Otherwise it can go a bit haywire with large groups.

**Comment by timtomch** [comment]
Noted. I've used appear.in in the past, found it a bit more resilient for larger groups, but at least one participant never got her audio to work, so not ideal. Skype actually works pretty well, especially audio only. It does require everyone to have  Skype account, though.

**Comment by drjwbaker** [comment]
I like Skype as well. But yeah, accounts required.

**Comment by ostephens** [comment]
Skype OK for me as well

**Comment by pitviper6** [comment]
+1 for Belinda, and I've got a Skype acct.

**Comment by tracykteal** [comment]
Also +1 to Belinda, so let's confirm with her before sending out a calendar link. 

I can set up a BlueJeans link for the call. It handles multiple people well and no account or login is required. We use them for our SWC/DC Community and discussion calls.

**Comment by drjwbaker** [comment]
@tracykteal: if you recommend it, great.

**Comment by cmacdonell** [comment]
bluejeans is quite good.  It has nice moderator controls for muting people, etc.  For SWC/DC meetings it seems to handle 10+ people without any issues.  It's a paid service and fortunately the other carpentries pay the bill ;)

**Comment by drjwbaker** [comment]
Okay. Sounds like bluejeans is a good option then.

**Comment by tracykteal** [comment]
Great! I set up a meeting and an etherpad, and included the connection details in the etherpad.

Etherpad:  
[http://pad.software-carpentry.org/library-carpentry](http://pad.software-carpentry.org/library-carpentry)

Bluejeans connection:  
[https://bluejeans.com/809911137](https://bluejeans.com/809911137)
(phone in details in the etherpad)

**Comment by drjwbaker** [comment]
Great. We'll confirm once @weaverbel is back in action.

**Comment by drjwbaker** [comment]
# MEETING UPDATE

We are due to meet 6 October per details at https://github.com/data-lessons/librarycarpentry/issues/7#issuecomment-248121595 We will hopefully meet for no longer than one hour.

## Provisional Agenda

1) **Welcome** (JAMES)

2) **[Library Carpentry - state of play October 2016](https://github.com/data-lessons/librarycarpentry/issues/6#issue-174569669)** (ALL) OUTCOME: agree to proceed with this document as our working set of principles or to adapt; agree where this should be hosted; agree who should maintain this (volunteers needed!)

3) **Relationship to Software/Data Carpentry** (ref https://github.com/data-lessons/librarycarpentry/issues/7#issuecomment-245359513) (ALL) What do we think of these? How are we minded? OUTCOME: Steer on what we want (so that we can put that to SWC/LC for consideration)

4) **Where do we each want Library Carpentry to be in 6, 12, 18 months?** (ALL) OUTCOME: list of targets (more likely ones for at 6 months, more speculative ones for at 18 months) that can then be worked on and presented back to the community for consideration.

4) **AOB** (ALL)

Chair: James @drjwbaker

Scribe: TBC (see below)

## Actions

- read agenda and suggest changes/additions
- read links/documents
- find a scribe

**Comment by jezcope** [comment]
I'll volunteer to scribe if no-one else really wants to do it!

**Comment by drjwbaker** [comment]
Thanks @jezcope!

**Comment by drjwbaker** [comment]
Any comment on the interim principles for instructors document? https://github.com/data-lessons/librarycarpentry/issues/11

**Comment by chodacki** [comment]
Sorry for the silence, I have been on trips the past couple weeks.  

Quick update from me:
1. Instructor Training. I am a co-organizer for csv,conf (data conference http://csvconf.com ).  We are planning our next event in early May 2017 in Portland, OR.  I talked to DC/SWC about doing an instructor training focused on the Librarian community around that time.  What do people think?  I do have some funding for csv.conf and could possibility offer some travel awards to those in need if they attend both.  Right now, we are thinking May 1-2, 2017 for csv,conf so we could do this before or after that.  
2. Modules. I remember us discussing new module development.  Is there a list of topics/modules everyone is currently working one?  Maybe we can start a thread on that.  Seems like a good thing to organize the work being done.  
3. Twitter. I attended the Library Carpentry workshop at UC Berkeley.  Thank you Harrison and @jt14den  for a great two days!  While there I was trying to tweet out about the event and saw we don’t have a twitter presence so I registered the @LibCarpentry handle.  Let me know if you want the password. my email is john.chodacki@ucop.edu  Could be a good way for all of us to promote our work.   
4. DST4L.  I happened to be on a call with Chris from DST4L last week.  And I noticed James is at http://dst4l.info event in Copenhagen in December.  And Chris mentioned he was just with Belinda in Australia.   I remember on our last call, we talked about how DST4L is an interesting group to keep an eye on.  @drjwbaker , it would be good hear back about how the Dec event goes and if there is something we can learn. @weaverbel , any plans to incorporate that into your efforts?
5. PIDapalooza.  If anyone is in Iceland next week, let m know.  It would be good to meet up.  http://pidapalooza.eventbrite.com / http://pidapalooza.org my email is john.chodacki@ucop.edu

**Comment by jezcope** [comment]
Hey @chodacki! We were actually just puzzling over the mystery of the [LibCarpentry](https://twitter.com/libcarpentry) twitter account over at https://gitter.im/weaverbel/LibraryCarpentry so thanks for clearing that up! :smile:

Lots of conversation happening on the gitter channel — that might be your best bet for discovering modules in development. I agree we should have a list of them, issues and pull requests on https://github.com/librarycarpentry/librarycarpentry.github.io welcome!

**Comment by drjwbaker** [comment]
@chodacki 

1) sounds great. Route it through SWC to test out the interim LC-flavoured SWC workshop mechanism https://github.com/data-lessons/librarycarpentry/issues/10
2) [Python](https://github.com/data-lessons/library-python) is one. XSLT has been mooted. There is another I have forgotten..
4) Yeah, I'm looking forward to DS4L and checking in with Chris. We have slightly different agendas, but undoubtedly some crossover.

**Comment by weaverbel** [comment]
On a totally unrelated thing, I do now think Library Carpentry is a third Carpentry, and should stand alone. SWC and DC are both aimed at helping researchers be more efficient etc whereas LC is about helping a professional group skill up - so it's very different in kind.
I did raise this at SWC steering committee and I think people now agree with that view.

**Comment by drjwbaker** [comment]
Thanks for parking this here @weaverbel.
